name: Build packages self-hosted

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release name (format v1.2.3)"
        required: true

jobs:
  build:
    runs-on: sp-zen-tech-linux-x64

    steps:
      - uses: actions/checkout@v4

      - name: Validate release version format
        run: |
          version_regex="^v[0-9]+\.[0-9]+\.[0-9]+$"
          if [[ ! "${{ github.event.inputs.release_version }}" =~ $version_regex ]]; then
            echo "Error: Invalid release version format. Expected format: v1.2.3"
            exit 1
          fi

      - name: Run docker build
        run: |
          NON_INTERACTIVE=1 FORCE_REBUILD_CONTAINER=1 ./build_in_docker.sh tdx

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          tag_name: "${{ github.event.inputs.release_version }}"
          release_name: "Release ${{ github.event.inputs.release_version }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/tdx/package-tdx.tar.gz
          asset_name: package-tdx.tar.gz
          asset_content_type: application/gzip
