name: Build TDX Test Image

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version (format v1.2.3)"
        required: true
        
jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-utils cloud-image-utils qemu-system-x86

    - name: Download Ubuntu 24.04 minimal cloud image
      run: |
        wget https://cloud-images.ubuntu.com/minimal/daily/noble/current/noble-minimal-cloudimg-amd64.img

    - name: Create cloud-init config
      run: |
        cat << EOF > cloud-init.cfg
        #cloud-config
        
        # Set password authentication
        ssh_pwauth: true
        chpasswd:
          expire: false
          list:
            - ubuntu:ubuntu123

        # Create default user
        users:
          - default
          - name: ubuntu
            sudo: ALL=(ALL) NOPASSWD:ALL
            shell: /bin/bash
            plain_text_passwd: 'ubuntu123'
            lock_passwd: false
            
        # Basic packages
        packages:
          - software-properties-common
          - build-essential
          
        package_update: true
        package_upgrade: true
        
        # TDX repo
        apt:
          sources:
            tdx-attestation:
              source: "ppa:tdx-attestation-release"

        # Install TDX tools
        runcmd:
          - apt-get install -y --allow-downgrades libtdx-attest-dev trustauthority-cli
          - cd /usr/share/doc/libtdx-attest-dev/examples/ && make
        EOF

    - name: Create cloud-init ISO
      run: |
        cloud-localds cloud-init-${{ github.event.inputs.release_version }}.iso cloud-init.cfg

    - name: Prepare VM image
      run: |
        qemu-img convert -O qcow2 noble-minimal-cloudimg-amd64.img tdx-test-${{ github.event.inputs.release_version }}.qcow2
        qemu-img resize tdx-test-${{ github.event.inputs.release_version }}.qcow2 +5G

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.release_version }}
        release_name: "TDX Test Image ${{ github.event.inputs.release_version }}"
        draft: false
        prerelease: false
        body: |
          TDX test image based on Ubuntu 24.04 minimal
          
          Components:
          - Base: noble-minimal-cloudimg-amd64
          - Cloud-init configuration for TDX setup
          - Image size: base + 5GB
          
          VM Credentials:
          - Login: ubuntu
          - Password: ubuntu123
          
          Usage:
          1. Download both .qcow2 and .iso files
          2. Use them together to start the VM
          3. First boot will install TDX components

    - name: Upload VM Image
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./tdx-test-${{ github.event.inputs.release_version }}.qcow2
        asset_name: tdx-test-${{ github.event.inputs.release_version }}.qcow2
        asset_content_type: application/octet-stream

    - name: Upload Cloud-Init ISO
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cloud-init-${{ github.event.inputs.release_version }}.iso
        asset_name: cloud-init-${{ github.event.inputs.release_version }}.iso
        asset_content_type: application/x-iso9660-image
