name: Build packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on:  ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev \
          debhelper-compat=12 meson ninja-build libglib2.0-dev python3-pip nasm iasl \
          git bc cpio kmod rsync zstd checkinstall libslirp-dev
          git config --global user.email "youremail@yourdomain.com"
          git config --global user.name "Your Name"

          mkdir -p $RUNNER_TEMP/build

      - name: Prepare patches
        run: |
          source ./scripts/build.sh
          preparePatches $RUNNER_TEMP/build

      - name: Build kernel
        run: |
          source ./scripts/build.sh
          build_kernel_packages $RUNNER_TEMP/build $(readlink -f ./config config-6.8.0-45-generic)
